In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import duckdb

In [17]:
con = duckdb.connect(r'C:\Users\marzieh\Documents\GitHub\Tennis-project\data\tennis.duckdb', read_only=True)
con.execute("SHOW TABLES").df()

                      name
0              _build_info
1            _import_audit
2            _schema_audit
3            _source_files
4      game_point_by_point
5         match_away_score
6          match_away_team
7              match_event
8         match_home_score
9          match_home_team
10             match_round
11            match_season
12              match_time
13        match_tournament
14             match_venue
15             match_votes
16                    odds
17       period_statistics
18                   power
19  v_match_event_readable
20        v_match_overview

In [41]:
query = """
    SELECT  period_1,
            period_2,
            period_3,
            period_4,
            period_5
    FROM match_time
    WHERE   period_1 IS NOT NULL AND
            match_id IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY match_id
        ORDER BY match_id
    ) = 1
"""
df = con.execute(query).df()
df

       period_1  period_2  period_3  period_4  period_5
0          3182      1960      2034      <NA>      <NA>
1          2508      2868      2528      <NA>      <NA>
2          3359      7619      3338      <NA>      <NA>
3          2377      3552      3386      <NA>      <NA>
4          2437      3616      <NA>      <NA>      <NA>
...         ...       ...       ...       ...       ...
11084      1863      2789      <NA>      <NA>      <NA>
11085      3087      3332      1792      <NA>      <NA>
11086      1867      2077      <NA>      <NA>      <NA>
11087         5       138      <NA>      <NA>      <NA>
11088      3185      2588      <NA>      <NA>      <NA>

[11089 rows x 5 columns]

In [46]:
cols = ["period_1", "period_2", "period_3", "period_4", "period_5"]

for col in cols:
    df[col] = df[col].where(df[col].isna() | (df[col] >= 300))

df

       period_1  period_2  period_3  period_4  period_5
0        3182.0      1960      2034      <NA>      <NA>
1        2508.0      2868      2528      <NA>      <NA>
2        3359.0      7619      3338      <NA>      <NA>
3        2377.0      3552      3386      <NA>      <NA>
4        2437.0      3616      <NA>      <NA>      <NA>
...         ...       ...       ...       ...       ...
11084    1863.0      2789      <NA>      <NA>      <NA>
11085    3087.0      3332      1792      <NA>      <NA>
11086    1867.0      2077      <NA>      <NA>      <NA>
11087       NaN      <NA>      <NA>      <NA>      <NA>
11088    3185.0      2588      <NA>      <NA>      <NA>

[11089 rows x 5 columns]

In [52]:
df.fillna(0).sum(axis=1).mean()

np.float64(6875.089818739291)